name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Get the latest release tag
        id: get_latest_tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${ secrets.TOKEN }}
          draft: true
          prerelease: true
        env:
            DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
      - name: Bump version and create tag
        id: tag
        uses: mathieudutour/github-tag-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_BUMP: minor
          TAG_PREFIX: v
          DRY_RUN: false
        with:
          ref: ${{ github.ref }}
          message: Bump version to v${{ steps.tag.outputs.new_tag }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          body: This is the release notes for version ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false